[build]
  command = "npx expo export -p web"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://calendar-mvp-u2s7.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://calendar-mvp-u2s7.onrender.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200